2017-02-06 03:02:44,757 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: washingtondc neigh:  city: Washington state: DC zipcode: 20001 url: 0 bedroom_no: 0 craigs_price: 0 estate_url: http://www.estately.com/DC/20001/sold?min_bed=1 bed: 4 home_price: 850000.0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\washingtondc_home.py", line 75, in <module>
    today_file_format = datetime.datetime.strptime(today_file, '%Y-%m-%d').date()
  File "C:\Python27\lib\_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '0' does not match format '%Y-%m-%d'
2017-02-06 05:19:06,117 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: miami neigh:  city: Miami state: FL zipcode: 33160 url: 0 bedroom_no: 0 craigs_price: 0 estate_url: http://www.estately.com/FL/33160/sold?min_bed=1 bed: 2 home_price: 1060000.0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\miami_home.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-02-06 05:20:09,749 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\richmond_home.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-02-06 05:20:53,977 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\sf_home.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-02-06 05:21:02,078 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\baltimore_home.py", line 75, in <module>
    today_file_format = datetime.datetime.strptime(today_file, '%Y-%m-%d').date()
  File "C:\Python27\lib\_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d'
2017-02-07 03:32:54,575 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: washingtondc neigh:  city: Washington state: DC zipcode: 20018 url: 0 bedroom_no: 0 craigs_price: 0 estate_url: http://www.estately.com/DC/20018/sold?min_bed=1 bed: 4 home_price: 601675.0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\washingtondc_home.py", line 75, in <module>
    today_file_format = datetime.datetime.strptime(today_file, '%Y-%m-%d').date()
  File "C:\Python27\lib\_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '0' does not match format '%Y-%m-%d'
2017-02-07 03:34:14,578 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\miami_home.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-02-07 04:00:28,266 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: richmond neigh:  city: Henrico state: VA zipcode: 23228 url: 0 bedroom_no: 0 craigs_price: 0 estate_url: http://www.estately.com/VA/23228/sold?min_bed=1 bed: 3 home_price: 105799.0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\richmond_home.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-02-07 04:01:19,204 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\sf_home.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-02-07 04:01:26,573 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\baltimore_home.py", line 75, in <module>
    today_file_format = datetime.datetime.strptime(today_file, '%Y-%m-%d').date()
  File "C:\Python27\lib\_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d'
2017-02-08 03:00:36,605 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\washingtondc_home.py", line 75, in <module>
    today_file_format = datetime.datetime.strptime(today_file, '%Y-%m-%d').date()
  File "C:\Python27\lib\_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '0' does not match format '%Y-%m-%d'
2017-02-08 03:01:36,240 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\miami_home.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-02-08 03:22:28,186 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: richmond neigh:  city: Henrico state: VA zipcode: 23294 url: 0 bedroom_no: 0 craigs_price: 0 estate_url: http://www.estately.com/VA/23294/sold?min_bed=1 bed: 3 home_price: 174900.0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\richmond_home.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-02-08 04:09:23,842 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: sanfrancisco neigh:  city: San Francisco state: CA zipcode: 94158 url: 0 bedroom_no: 0 craigs_price: 0 estate_url: http://www.estately.com/CA/94158/sold?min_bed=1 bed: 2 home_price: 1000000.0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\sf_home.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-02-08 04:09:29,605 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\baltimore_home.py", line 75, in <module>
    today_file_format = datetime.datetime.strptime(today_file, '%Y-%m-%d').date()
  File "C:\Python27\lib\_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d'
